Repository polybar/polybar, pull requests merged in 2020-01, with the labels that each got.

#1990 fix(net): Query IP addresses for tun/ tap devices
  src/adapters/net.cpp
Labels: bug

#1976 Add Fedora installation instructions
  README.md
Labels: Packaging

#1993 fix(test): Gtest compilation failure
  tests/CMakeLists.txt.in
Labels: build

#1984 fix(xworkspaces): Show _NET_NUMBER_OF_DESKTOPS desktops
  src/modules/xworkspaces.cpp
Labels: bug
